### PR TITLE
Restructures the Error Handling and Starts Async/Await Conversion. Covers Patient and MessageTemplate APIs

### PR DESCRIPTION
**Pull request by epalaz**
I created this PR first to not create a gigantic single PR for whole refactoring of error handling and asyc/await transition. I have  started refactoring with messageTemplate and patient APIs. I will hold back the rest of the PRs until we think this structure is ok. If there are suggestions for changes I can incorporate those into rest of changes after this PR gets merged.

### CODE REVIEW

**Review by rweald — COMMENTED** [review]
Overall I really like this cleanup and moving the error handling over to this more standardized system. Basically creates something very akin to what Rails already does out of the box. 

My biggest concern / piece of feedback is really whether we want to be doing param validation and parsing at the controller/request level anyway? I've already noticed a couple times how we can accidentally end up with inaccurate / invalid data in the database when data in inserted through non controller functions. 

Probably outside the direct scope of this change, since I think it's likely valuable regardless, but seeing all the changes to `src/routes/patient.api.ts` made to think about whether this logic should be pushed down deeper into the domain layers. At which point it probably makes more sense to use a mechanism other than throwing exceptions to handle validation issues. More akin to rails `valid?` and `save => boolean` methods. The funny thing being we already have some of these validations duplicated at the mongoose layer anyway. 

@epalaz

**Comment by epalaz** [comment]
@rweald What we can do is, move request validations above controller with a middleware function. Similar to auth function that we add before for checking required fields (missing or not) etc. These wouldn't go into validation details like options for a field in Patient document. These Modal related ones would be handled by modal functions that we can create.

**Comment by rweald** [comment]
yeah I don't think we need to lift it up higher in the request stack. More push all the validations down outside of the request / response lifecycle. That way the same validations get applied universally any time you are attempting to create a record, whether that's via HTTP API request, background cron task, or deploy migration. 

Not a huge deal for now though. Something we can refactor towards later, as we add more model layer code.

**Comment by epalaz** [comment]
I agree. I will move those down to the model layer. Pushing up for cases where we would have a field unrelated to a model but this is really unlikely for now.

**Comment by rweald** [comment]
Yeah totally! Even if we do end up with a case like that, I personally tend to like to model that stuff using some sort of non persisted domain model that can still handle validation for complex data types outside of the controller.

**Pull request closed without merging**
